on:
  pull_request:
    branches: [ "master" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    name: Build # todo -- feature matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        feature: [ tempfile, r2 ]
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Build
        run: cargo build --no-default-features --features ${{ matrix.feature }} --verbose
      - name: Test
        run: cargo test --no-default-features --features ${{ matrix.feature }} --verbose
      - name: Lint
        run: cargo clippy --no-default-features --features ${{ matrix.feature }} --all-targets -- -D warnings
      - name: Lint
        run: cargo clippy --all-targets --all-features -- -D warnings
